var searchData=
[
  ['cache_20functions_16618',['Cache Functions',['../group___c_m_s_i_s___core___cache_functions.html',1,'']]],
  ['class_20marks_20example_16619',['Class Marks Example',['../group___class_marks.html',1,'']]],
  ['cmsis_16620',['CMSIS',['../group___c_m_s_i_s.html',1,'']]],
  ['cmsis_20core_20instruction_20interface_16621',['CMSIS Core Instruction Interface',['../group___c_m_s_i_s___core___instruction_interface.html',1,'']]],
  ['cmsis_20core_20register_20access_20functions_16622',['CMSIS Core Register Access Functions',['../group___c_m_s_i_s___core___reg_acc_functions.html',1,'']]],
  ['cmsis_20global_20defines_16623',['CMSIS Global Defines',['../group___c_m_s_i_s__glob__defs.html',1,'']]],
  ['cmsis_20simd_20intrinsics_16624',['CMSIS SIMD Intrinsics',['../group___c_m_s_i_s___s_i_m_d__intrinsics.html',1,'']]],
  ['complex_20conjugate_16625',['Complex Conjugate',['../group__cmplx__conj.html',1,'']]],
  ['complex_20dot_20product_16626',['Complex Dot Product',['../group__cmplx__dot__prod.html',1,'']]],
  ['complex_20fft_20functions_16627',['Complex FFT Functions',['../group___complex_f_f_t.html',1,'']]],
  ['complex_20fft_20tables_16628',['Complex FFT Tables',['../group___c_f_f_t___c_i_f_f_t.html',1,'']]],
  ['complex_20magnitude_16629',['Complex Magnitude',['../group__cmplx__mag.html',1,'']]],
  ['complex_20magnitude_20squared_16630',['Complex Magnitude Squared',['../group__cmplx__mag__squared.html',1,'']]],
  ['complex_20math_20functions_16631',['Complex Math Functions',['../group__group_cmplx_math.html',1,'']]],
  ['complex_20matrix_20multiplication_16632',['Complex Matrix Multiplication',['../group___cmplx_matrix_mult.html',1,'']]],
  ['complex_2dby_2dcomplex_20multiplication_16633',['Complex-by-Complex Multiplication',['../group___cmplx_by_cmplx_mult.html',1,'']]],
  ['complex_2dby_2dreal_20multiplication_16634',['Complex-by-Real Multiplication',['../group___cmplx_by_real_mult.html',1,'']]],
  ['configuration_20functions_16635',['Configuration functions',['../group___e_x_t_i___exported___functions___group1.html',1,'']]],
  ['configuration_5fsection_5ffor_5fcmsis_16636',['Configuration_section_for_CMSIS',['../group___configuration__section__for___c_m_s_i_s.html',1,'']]],
  ['controller_20functions_16637',['Controller Functions',['../group__group_controller.html',1,'']]],
  ['convert_2016_2dbit_20integer_20value_16638',['Convert 16-bit Integer value',['../group__q15__to__x.html',1,'']]],
  ['convert_2032_2dbit_20floating_20point_20value_16639',['Convert 32-bit floating point value',['../group__float__to__x.html',1,'']]],
  ['convert_2032_2dbit_20integer_20value_16640',['Convert 32-bit Integer value',['../group__q31__to__x.html',1,'']]],
  ['convert_208_2dbit_20integer_20value_16641',['Convert 8-bit Integer value',['../group__q7__to__x.html',1,'']]],
  ['convolution_16642',['Convolution',['../group___conv.html',1,'']]],
  ['convolution_20example_16643',['Convolution Example',['../group___convolution_example.html',1,'']]],
  ['convolutional_20neural_20network_20example_16644',['Convolutional Neural Network Example',['../group___c_n_n_example.html',1,'']]],
  ['core_20debug_20registers_20_28coredebug_29_16645',['Core Debug Registers (CoreDebug)',['../group___c_m_s_i_s___core_debug.html',1,'']]],
  ['core_20definitions_16646',['Core Definitions',['../group___c_m_s_i_s__core__base.html',1,'']]],
  ['core_20register_20bit_20field_20macros_16647',['Core register bit field macros',['../group___c_m_s_i_s__core__bitfield.html',1,'']]],
  ['correlation_16648',['Correlation',['../group___corr.html',1,'']]],
  ['cortex_16649',['CORTEX',['../group___c_o_r_t_e_x.html',1,'(Global Namespace)'],['../group___c_o_r_t_e_x___l_l.html',1,'(Global Namespace)']]],
  ['cortex_20_5fsystick_20clock_20source_16650',['CORTEX _SysTick clock source',['../group___c_o_r_t_e_x___sys_tick__clock__source.html',1,'']]],
  ['cortex_20exported_20constants_16651',['CORTEX Exported Constants',['../group___c_o_r_t_e_x___exported___constants.html',1,'(Global Namespace)'],['../group___c_o_r_t_e_x___l_l___exported___constants.html',1,'(Global Namespace)']]],
  ['cortex_20exported_20functions_16652',['CORTEX Exported Functions',['../group___c_o_r_t_e_x___l_l___exported___functions.html',1,'']]],
  ['cortex_20exported_20types_16653',['Cortex Exported Types',['../group___c_o_r_t_e_x___exported___types.html',1,'']]],
  ['cortex_20preemption_20priority_20group_16654',['CORTEX Preemption Priority Group',['../group___c_o_r_t_e_x___preemption___priority___group.html',1,'']]],
  ['cortex_20private_20macros_16655',['CORTEX Private Macros',['../group___c_o_r_t_e_x___private___macros.html',1,'']]],
  ['cortex_5fexported_5ffunctions_16656',['CORTEX_Exported_Functions',['../group___c_o_r_t_e_x___exported___functions.html',1,'']]],
  ['cortex_5fexported_5ffunctions_5fgroup1_16657',['CORTEX_Exported_Functions_Group1',['../group___c_o_r_t_e_x___exported___functions___group1.html',1,'']]],
  ['cortex_5fexported_5ffunctions_5fgroup2_16658',['CORTEX_Exported_Functions_Group2',['../group___c_o_r_t_e_x___exported___functions___group2.html',1,'']]],
  ['cosine_16659',['Cosine',['../group__cos.html',1,'']]],
  ['crc_16660',['CRC',['../group___c_r_c.html',1,'']]],
  ['crc_20exported_20constants_16661',['CRC Exported Constants',['../group___c_r_c___exported___constants.html',1,'']]],
  ['crc_20exported_20functions_16662',['CRC Exported Functions',['../group___c_r_c___exported___functions.html',1,'']]],
  ['crc_20exported_20macros_16663',['CRC Exported Macros',['../group___c_r_c___exported___macros.html',1,'']]],
  ['crc_20exported_20types_16664',['CRC Exported Types',['../group___c_r_c___exported___types.html',1,'']]],
  ['crc_20private_20macros_16665',['CRC Private Macros',['../group___c_r_c___private___macros.html',1,'']]]
];
